name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]  # develop ë¸Œëœì¹˜ì— pushê°€ ì¼ì–´ë‚  ë•Œ ì‹¤í–‰

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ì €ì¥ì†Œ ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - uses: actions/checkout@v3

      # JDK 17 ì„¤ì •
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # application.yml íŒŒì¼ ìƒì„±
      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
        shell: bash

      # Gradleë¡œ ë¹Œë“œ
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # Docker ì´ë¯¸ì§€ ë¹Œë“œ ë° í‘¸ì‹œ (ğŸš¨ `--build-arg` ì¶”ê°€!)
      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --no-cache -t ${{ secrets.DOCKER_REPO }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_REPO }}:${{ github.sha }}   

      # ì„œë²„ ë°°í¬
      - name: Deploy to server with Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker-compose down
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker-compose -f docker-compose.yml up -d
            sudo docker image prune -f
      # jar íŒŒì¼ëª… í™•ì¸
      - name: Show built files
        run: |
          ls -alh build/libs